export enum TokenPackages {
  "free" = "free",
  "starter" = "starter",
  "pro" = "pro",
  "expert" = "expert",
}

export const tokenPackages = [
  {
    id: TokenPackages.free,
    name: "Free Trial",
    tokens: 2,
    price: 0.0,
    description: "Get started with a few courses for free",
    features: [
      "2 tokens to create courses",
      "1 hour max video length per course",
      "Full access to AI summaries and quizzes",
      "No credit card required",
    ],
    popular: false,
    color: "gray",
    link: "",
    priceId: "",
  },
  {
    id: TokenPackages.starter,
    name: "Starter Pack",
    tokens: 10,
    price: 4.99,
    description: "Create up to 10 courses at a budget-friendly price",
    features: [
      "10 tokens to create courses",
      "Up to 5 hours video length per course",
      "Same great AI summaries and quizzes",
      "Just 49¢ per course ($4.99 total)",
    ],
    popular: false,
    color: "blue",
    link: "https://buy.stripe.com/test_9AQ4hv6BDdZnbRuaEE",
    testPriceId: "price_1RF6By4K0ftCSNroD4p0DJzW",
    priceId: "price_1RIcFFKS0ZvvdOIEhGlReozz",
  },
  {
    id: TokenPackages.pro,
    name: "Pro Pack",
    tokens: 30,
    price: 9.99,
    description: "Best value for regular creators",
    features: [
      "30 tokens to create courses",
      "Up to 5 hours video length per course",
      "Only 33¢ per course ($9.99 total)",
      "Perfect for consistent learners",
    ],
    popular: true,
    color: "cyan",
    link: "https://buy.stripe.com/test_eVa15j1hjf3r6xa7st",
    testPriceId: "price_1RFNJ44K0ftCSNroAIIjDE2J",
    priceId: "price_1RIcFBKS0ZvvdOIE3gkVDqbO",
  },
  {
    id: TokenPackages.expert,
    name: "Expert Pack",
    tokens: 100,
    price: 19.99,
    description: "Create dozens of courses at our lowest per-token price",
    features: [
      "100 tokens to create courses",
      "Up to 5 hours video length per course",
      "Only 20¢ per course ($19.99 total)",
      "Ideal for schools and organizations",
    ],
    popular: false,
    color: "purple",
    link: "https://buy.stripe.com/test_eVa15j1hjf3r6xa7st",
    testPriceId: "price_1RFQvd4K0ftCSNroopkxw00Y",
    priceId: "price_1RIcF8KS0ZvvdOIEITU7JFuC",
  },
] as const;
