export enum TokenPackages {
  "free" = "free",
  "starter" = "starter",
  "pro" = "pro",
  "expert" = "expert",
}

export const tokenPackages = [
  {
    id: TokenPackages.free,
    name: "Free Trial",
    tokens: 2,
    price: 0.0,
    description: "Get started with a few courses for free",
    features: [
      "2 basic courses (1 hours max each)",
      "Try summaries and quizzes",
      "No credit card required",
    ],
    popular: false,
    color: "gray",
    link: "",
    priceId: "",
  },
  {
    id: TokenPackages.starter,
    name: "Starter Pack",
    tokens: 10,
    price: 4.99,
    description: "Enough tokens to create up to 10 basic courses",
    features: [
      "No feature gating",
      "Flashcards unlocked",
      "Enhanced course creation settings",
      "Create 10 courses",
    ],
    popular: false,
    color: "blue",
    link: "https://buy.stripe.com/test_9AQ4hv6BDdZnbRuaEE",
    priceId: "price_1RF6By4K0ftCSNroD4p0DJzW",
  },
  {
    id: TokenPackages.pro,
    name: "Pro Pack",
    tokens: 30,
    price: 9.99,
    description: "Best value for regular creators",
    features: [
      "Discounted token rate",
      "Great for power users",
      "Create 30 courses",
    ],
    popular: true,
    color: "cyan",
    link: "https://buy.stripe.com/test_eVa15j1hjf3r6xa7st",
    priceId: "price_1RFNJ44K0ftCSNroAIIjDE2J",
  },
  {
    id: TokenPackages.expert,
    name: "Expert Pack",
    tokens: 100,
    price: 19.99,
    description: "Create dozens of courses with premium AI options",
    features: [
      "Biggest discount",
      "Ideal for educators and teams",
      "Create 100 courses",
    ],
    popular: false,
    color: "purple",
    link: "https://buy.stripe.com/test_eVa15j1hjf3r6xa7st",
    priceId: "price_1RFQvd4K0ftCSNroopkxw00Y",
  },
] as const;
